In [ ]:
# addition = np.add()

import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,2,5,4])

new_arr = np.add(arr1,arr2)
print(new_arr)

[4 6 5 9 9]


In [2]:
#subtraction = np.subtracte()

import numpy as np

arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,2,5,4])

new_arr = np.subtract(arr2,arr1)
print(new_arr)


[ 2  2 -1  1 -1]


In [3]:
# multiplication = np.multiply()


import numpy as np

arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,2,5,4])

new_arr = np.multiply(arr2,arr1)
print(new_arr)


[ 3  8  6 20 20]


In [5]:
# division = np.divide()

import numpy as np

arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,2,5,4])

new_arr = np.divide(arr2,arr1)
print(new_arr)

[3.         2.         0.66666667 1.25       0.8       ]


In [6]:
#power = np.power()

import numpy as np

arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,2,5,4])

new_arr = np.power(arr2,arr1)
print(new_arr)

[   3   16    8  625 1024]


# mod or remainder does the same thing == np.mod() or np.remainder()

In [2]:
import numpy as np

arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,2,5,4])

new_arr = np.mod(arr1,arr2)
new_arr1= np.remainder(arr1, arr2)
print(new_arr1)

print(new_arr)

[1 2 1 4 1]
[1 2 1 4 1]


# for both divider and remainder(mod)
  #divisionmode= divmod()
  It retuens two arrays first contain the quotient and second
  contains the remiander.

In [ ]:
import numpy as np

arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,2,5,4])

new_arr = np.divmod(arr2,arr1)
print(new_arr)

(array([3, 2, 0, 1, 0]), array([0, 0, 2, 1, 4]))


In [10]:
# absolute value = np.absolute() or abs() can be used

import numpy as np

arr1= np.array([1,-2,-3,4,5])


new_arr = np.absolute(arr1)
print(new_arr)

[1 2 3 4 5]
