# summation is the sum upto. n numbers. sum() method is used for this.



In [1]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])

arr= np.sum([arr1, arr2])
arr0 = np.add(arr1, arr2)
print(arr)

print(arr0)



20
[2 4 6 8]


In [4]:
# summation over an axis

import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])

arr= np.sum([arr1, arr2],axis=1)
arr0 = np.add(arr1, arr2)
print(arr0)

print(arr)



[2 4 6 8]
[10 10]


# cummulative sum 
 ''' 
 for array [1,2,3,4] it's cummulative sum is =[1, 1+2, 1+2+3, 1+2+3+4] 
 '''

 # cumsum(). method is used
 

In [5]:
import numpy as np

arr= np.array([1,2,3,4])
result= np.cumsum(arr)
print(result)


[ 1  3  6 10]
