# numpy provides sin() cos() and tan() as trignometric functions for numpy ufunc.

In [2]:
import numpy as np
x= np.sin(np.pi/2)
print(x)


1.0


In [3]:
import  numpy as np
x= np.array([np.pi, np.pi/2,np.pi/3])
y= np.cos(x)
print(y)


[-1.000000e+00  6.123234e-17  5.000000e-01]


In [4]:
# convert radian into angle

import numpy as np
arr= np.array([np.pi,np.pi/2,np.pi/3])
res = np.rad2deg(arr)
print(res)


[180.  90.  60.]


In [5]:
#convert degree into radian

import numpy as np
arr= np.array([180,45,90,135])
res = np.deg2rad(arr)
print(res)


[3.14159265 0.78539816 1.57079633 2.35619449]


# finding the angles from value

In [6]:
# arc....sin,cos,tan......()

import numpy as np
ar= np.array([1,2.5,1.5,0])
res= np.arctan(ar)
print(res)


[0.78539816 1.19028995 0.98279372 0.        ]


# numpy provides hypot() function for hypotenous

In [8]:
import numpy as np

base=3
perp= 4

x= np.hypot(base,perp)
print(x)


5.0


# same procedure for hyperbolic functions like sinh(), cosh() and tanh()