# set operation takes only 1d array .

In [1]:
# create set 

import numpy as np

arr= np.array([1,2,1,3,4,5,3,3,2])
set= np.unique(arr)
print(set)


[1 2 3 4 5]


In [2]:
# for multiple array union1d() is used

import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,5,6])

print(np.union1d(arr1,arr2))


[1 2 3 4 5 6]


assume_unique is used to speed up computation and should be true while doing set operation


In [3]:
# for intersection -> intersect1d() is used

import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,5,6])

x=np.intersect1d(arr1,arr2,assume_unique=True)
print(x)





[3 4 5]


In [4]:
# finding difference -> setdiff1d(). is used

import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,5,6])

new= np.setdiff1d(arr1,arr2,assume_unique=True)

print(new)




[1 2]


In [8]:
# finding symmetric difference i.e the values that are not present in both sets

import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([3,4,5,6])

new = np.setxor1d(arr1,arr2,assume_unique= True)

print(new)


[1 2 6]
