In [4]:
import numpy as np
num_aray = np.array([1,2,3,4,5,5])
print(num_aray)
array=np.zeros((1,5))
print(array)



[1 2 3 4 5 5]
[[0. 0. 0. 0. 0.]]


In [5]:
#3 dimensional array
import numpy as np
arr = np.array([[[1,4,6,2],[1,2,3,4]], [[0,8,7,3],[2,3,4,2]]])
print(arr)


[[[1 4 6 2]
  [1 2 3 4]]

 [[0 8 7 3]
  [2 3 4 2]]]


In [7]:
#using ndmin to define matrix
import numpy as np
arr= np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimension:",arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimension: 5
