In [1]:
# copy and change the og array

import numpy as np
aee= np.array([1,2,3,4,5])
c=aee.copy()
aee[1]=0
print(aee)
print(c)


[1 0 3 4 5]
[1 2 3 4 5]


In [2]:
#view and change the og array

import numpy as np
arr= np.array([1,2,3,4])
v= arr.view()
arr[0]= 80
print(arr)
print(v)


[80  2  3  4]
[80  2  3  4]


In [3]:
# change the view and see the result 

import numpy as np
a= np.array([1,2,3])
v= a.view()
v[1]=100

print(a)
print(v)


[  1 100   3]
[  1 100   3]


In [5]:
# base as an attribute of numpy

In [ ]:
import numpy as np
arr= np.array([1,2,3,4])

x= arr.copy()
y= arr.view()

print(x.base) #-> returns none as it has it's own data
print(y.base) # -> returns the original array as it is a view of the original array



None
[1 2 3 4]
