In [1]:
# reshaping from 1d to 2d 
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
#reshaping from 1d to 3d
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array = arr.reshape(2,3,2)
print(new_array)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
# check if copy or view
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr= arr.reshape(2,3,2).base
print(new_arr) # returns the og array





[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
# reshaping from 2d to 3d 
import numpy as np
arr = np.array([[1,2,3],[2,3,4]])
n_arr= arr.reshape(1,2,3)
print(n_arr)
print(n_arr.shape)
print(n_arr.size)
print(arr.ndim)
print(n_arr.ndim)


[[[1 2 3]
  [2 3 4]]]
(1, 2, 3)
6
2
3


In [ ]:
#unknown dimension
# converting 1d to 3d with 8 elements 
#remember you can have only one unknown dimension

import numpy as np
arr= np.array([1,2,3,4,5,6,7,8]) 
new_arr= arr.reshape(2,4,-1)
print(new_arr)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]


In [16]:
#flattening the array = converting to 1d array from the multi-d array

import numpy as np
arr= np.array([[1,2,3],[3,4,5]])
n_a= arr.reshape(-1) 
ne_ar= arr.flatten()
new_arr= arr.ravel()

print(ne_ar.base)
print(new_arr.base)

print(n_a.base)


None
[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]]
