'''
syntax for slicing :

variable[start,stop,end]

'''


In [1]:
import numpy as np
arr= np.array([10,20,30,40,50,60])
print(arr[1:3])
print(arr[:4])  # begining to end
print(arr[1:5:3])
print(arr[::2])   #start to end with 2 steps gap
print(arr[::-1]) # reverse the order (end->stop)


[20 30]
[10 20 30 40]
[20 50]
[10 30 50]
[60 50 40 30 20 10]


## fancy indexing = select the multiple elemnts withot chnaging the original elemnet i.e creates a copy

notice the syntax of writing this 


In [6]:
import numpy as np
arr= np.array([10,20,30,40,50,60])
print(arr[[1,4,5]])



[20 50 60]


## filtering = it is the concept based on boolean masking
returns while true 

In [1]:
import numpy as np
arr= np.array([10,20,30,40,50,60])
print(arr[arr>90])


[]


In [9]:
# slicing for 2 or multiple dimensions

import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1:5]) # -> gives the value from first elemnet 
print(arr[1,2:4]) #-> givrs the value from second element
print(arr[0:2,3]) #-> gives the value from 3rd column of both the elements
print(arr[:,1:4]) #-> gives the value from 1st to 3rd column of both the elements





[2 3 4 5]
[8 9]
[4 9]
[[2 3 4]
 [7 8 9]]
