In [1]:
# iteration of 1d array

import numpy as np
arr= np.array([1,2,3,4])
for x in arr:
    print(x)

    


1
2
3
4


In [2]:
# for 2d arrray

import numpy as np
arr= np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    print(x)
    

[1 2 3 4]
[5 6 7 8]


In [3]:
#iterate scalar element of 2d array
import numpy as np
arr= np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


In [ ]:
#for 3d array
import numpy as np
arr= np.array([[[1,2,3,4],[5,6,7,8]],[[1,4,5,7],[9,7,2,5]]])
for x in arr:
     for y in x:
        for z in y:
            print(z)
            



nditer() = easy function for accessing scalar element from multiple dimension

In [ ]:
import numpy as np
arr= np.array([[[1,2,3],[2,3,4]],[[5,6,7],[3,4,5]]])
for x in np.nditer(arr):
    print(x)
    

Iterating array with different data types


In [21]:
import numpy as  np
arr=np.array([1,2,3,4])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)
    


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [25]:
#interating with different step size

import numpy as np
arr= np.array([[1,2,3,4],
               [5,6,7,7]])
# for x in np.nditer(arr[:, ::2]):
#     print(x)
print(arr[:, ::2])

[[1 3]
 [5 7]]


In [ ]:
# enumerate ( similar syntax for all dimensions)

In [27]:
import numpy as np
arr= np.array([1,2,3])
for ind, x in np.ndenumerate(arr):
    print(ind,x)
    

(0,) 1
(1,) 2
(2,) 3
