In [9]:
# concatenate()

import numpy as np
arr1= np.array([1,2,3])
arr2 = np.array([4,5,6])
arr= np.concatenate((arr1,arr2),axis=0)
print(arr)


[1 2 3 4 5 6]


In [2]:
#join two 2d array

import numpy as np
arr1= np.array([[1,2,3],[2,3,4]])
arr2 = np.array([[3,2,3],[2,6,4]])
arr =np.concatenate((arr1,arr2),axis=1) 
print(arr)


[[1 2 3 3 2 3]
 [2 3 4 2 6 4]]


note:
1) axis =0 denotes row-wise concatenation
2) axis =1 denotes column-wise concatenation

In [8]:
#using stack for joining

import numpy as np
arr1= np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)




[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#use of hstack for horizontal stacking
import numpy as np
arr1= np.array([1,2,3,4])
arr2= np.array([9,8,7,6])
arr= np.hstack((arr1,arr2))
print(arr)
print(arr.ndim)

[1 2 3 4 9 8 7 6]
1


In [11]:
#use of vstack for verticle stacking
import numpy as np
arr1= np.array([1,2,3,4])
arr2= np.array([9,8,7,6])
arr= np.vstack((arr1,arr2))
print(arr)
print(arr.ndim)


[[1 2 3 4]
 [9 8 7 6]]
2


In [12]:
#use of dstack for verticle stacking
import numpy as np
arr1= np.array([1,2,3,4])
arr2= np.array([9,8,7,6])
arr= np.dstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]
3
