In [1]:
import numpy as np
arr= np.array([1,2,3,4,5,4,4])
x= np.where(arr==4)
print(x)


(array([3, 5, 6]),)


In [2]:
# search the indexes where the values are even
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2==0)
print(x)



(array([1, 3, 5, 7]),)


In [3]:
# search the indexes where the values are odd
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6]),)


#use of search sorted method
  this is used to maintain the search order.



In [4]:
import numpy as np
arr= np.array([10,6,7,8,9])
x= np.searchsorted(arr, 7) # default goes from left to right
print(x)



2


In [5]:
import numpy as np
arr= np.array([6,8,7,1])
x= np.searchsorted(arr,7,side='right') #now it searches from right to left
print(x)


4


In [7]:
# for multiple values

import numpy as np
arr= np.array([1,3,5,7,9])
x= np.searchsorted(arr,[2,4,6,8],side ='right')
print(x)



[1 2 3 4]
