where() method is used for searching the element.
It returns the index of that value.

In [1]:
import numpy as np
arr= np.array([1,2,3,4,5,4,4])
x= np.where(arr==4)
print(x)


(array([3, 5, 6]),)


# search the indexes where the values are even

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2==0)
print(x)



(array([1, 3, 5, 7]),)


In [3]:
# search the indexes where the values are odd
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6]),)


#use of search sorted method
  this is used to maintain the search order.



In [2]:
import numpy as np
arr= np.array([6,7,8,9,10])
x= np.searchsorted(arr, 7) # default goes from left to right
print(x)



1


np.searchsorted() method assumes that the array is already sorted in ascending order.
so,gives correct results if the array is sorted.
In below code the array is not sorted .

In [1]:
import numpy as np
arr= np.array([6,8,7,1])
x= np.searchsorted(arr,7,side='right') #now it searches from right to left
print(x)


4


In [7]:
# for multiple values

import numpy as np
arr= np.array([1,3,5,7,9])
x= np.searchsorted(arr,[2,4,6,8],side ='right')
print(x)



[1 2 3 4]


side ="right" matters only when there present duplicate values.

In [4]:
import numpy as np
arr= np.array([1,2,3,3,4,5,5,5,7])
print("for side left")
print(np.searchsorted(arr,[3,5],side='left'))

print("for side right")
print(np.searchsorted(arr,[3,5],side='right'))




for side left
[2 5]
for side right
[4 8]
