filtering means getting elemnts from existing array and makeing new array out of them .


In [1]:
import numpy as np
arr= np.array([23,5,12,57])
x=[True , False , False , True]
print(arr[x])


[23 57]


In [ ]:
# filtering those values greater than 30
import numpy as np
arr= np.array([1,5,7,35,8,45,356,342,3,67])
filter_arr =[]

for element in arr:
    if element > 30:
        filter_arr.append(True)
    else:
        filter_arr.append(False)


new_arr= arr[filter_arr]

print(filter_arr)
print(new_arr)
                 



[False, False, False, True, False, True, True, True, False, True]
[ 35  45 356 342  67]


In [3]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = []

for elemnt in arr:
    if elemnt%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

new_arr= arr[filter_arr]

print(filter_arr)
print(new_arr)

    

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [5]:
#creating filter directly from array

import numpy as np
arr= np.array([1,2,3,4,5,6])
filter_arr= arr > 2
new_arr= arr[filter_arr]
print(filter_arr)
print(new_arr)


[False False  True  True  True  True]
[3 4 5 6]
