In [11]:
# generate a random number from 0 to 100
from numpy import random
x= random.randint(100)
print(x)


31


In [33]:
#generate a float number between 0 to 1
from numpy import random
x= random.rand()
print(x)


0.5703226942093031


In [48]:
#generate a random array (1D)
from numpy import random
x= random.randint(100,size=(4))
print(x)

[14 76  6 99]


In [20]:
#generate a random 2D array from 0 to 100 with 3 rows having 5 elemnts

from numpy import random
x= random.randint(100,size=(3,5))
print(x)

[[13  5 84 19  0]
 [92  3 93 84 73]
 [70 80 91 13 98]]


In [61]:
#genration of random 2D float array
from numpy import random
x= random.rand(3,5)
print(x)


[[0.35917607 0.69491497 0.01179352 0.066109   0.03390116]
 [0.46363097 0.45832944 0.70893577 0.18068131 0.61195067]
 [0.09699366 0.10114496 0.74720869 0.09826351 0.24100793]]


In [77]:
#generate a random number from array

from numpy import random
x= random.choice([3,2,5,7])
print(x)

3


In [89]:
from numpy import random
x= random.choice([3,5,9,7],size=(3,5))
print(x)


[[5 9 5 7 5]
 [7 7 7 3 3]
 [3 9 7 7 5]]
