In [1]:
# generate a random number from 0 to 100
from numpy import random
x= random.randint(100)
print(x)


77


In [18]:
#generate a float number between 0 to 1
from numpy import random
x= random.rand()
print(x)


0.9371037239749093


In [ ]:
#generate a random array (1D)
from numpy import random
x= random.randint(100,size=(4))
print(x)

[73 69 90 66]


In [20]:
#generate a random 2D array from 0 to 100 with 3 rows having 5 elemnts

from numpy import random
x= random.randint(100,size=(3,5))
print(x)

[[13  5 84 19  0]
 [92  3 93 84 73]
 [70 80 91 13 98]]


In [ ]:
#genration of random 2D float array
from numpy import random
x= random.rand(3,5)
print(x)


[[0.97172605 0.37270877 0.38640369 0.60918014 0.54307312]
 [0.86363479 0.27873995 0.13337791 0.18467866 0.22108501]
 [0.86503794 0.99212193 0.85407642 0.93329608 0.37982276]]


In [33]:
#generate a random number from array

from numpy import random
x= random.choice([3,2,5,7])
print(x)

7


In [34]:
from numpy import random
x= random.choice([3,5,9,7],size=(3,5))
print(x)


[[7 9 9 5 7]
 [9 5 5 7 9]
 [7 9 9 7 3]]
