In [5]:
from numpy import random
import numpy as np
x= random.choice([3,5,7,9],p=[0.2,0.5,0.3,0.0],size=(3,5))
print(x)

# for counting the occurance of the values in the array we can use np.sum() function
# c= np.sum(x==5)
# print(c)
# d=np.sum(x==7)
# print(d)
# e= np.sum(x==3)
# print(e)




[[3 7 7 5 5]
 [3 3 7 7 7]
 [5 5 7 3 5]]
