# shuffle() makes the changes in original array

In [13]:
from numpy import random
import numpy as np

arr= np.array([3,2,4,51])
random.shuffle(arr)
print(arr)

[51  4  3  2]


#permutation() rearranges the original array and returns a new array while leaving 
the og arry unchanged

In [17]:
from numpy import random
import numpy as np

arr= np.array([3,4,7,1,9])
print(random.permutation(arr))
print(arr)


[1 4 7 3 9]
[3 4 7 1 9]
