In [ ]:
# shuffle() makes the changes in original array
from numpy import random
import numpy as np

arr= np.array([3,2,4,51])
random.shuffle(arr)
print(arr)

[ 4 51  3  2]


In [11]:
#permutation() rearranges the original array and returns a new array while leaving the og arry unchanged

from numpy import random
import numpy as np

arr= np.array([3,4,7,1,9])
print(random.permutation(arr))
print(arr)


[9 3 7 4 1]
[3 4 7 1 9]
